# Kitty config

font_size 14.0
enable_audio_bell no 
allow_remote_control yes
font_family "MesloLGS Nerd Font Mono"
bold_font auto
italic_font auto
bold_italic_font auto
allow_remote_control yes
listen_on unix:/tmp/kitty-nvim.sock
# Fallback for Nerd Font glyph ranges used by Neovim plugins/dashboard icons
symbol_map U+E000-U+F8FF Symbols Nerd Font
symbol_map U+F0000-U+FFFFD Symbols Nerd Font
